### ISSUE TITLE
Can't connect to remote server - disconnect_not_host

### ISSUE THREAD

**Issue by pandalabs-dev** [honserver/honserver#15]
I've managed to set up a remote server with these libraries. 

But when I try to connect to it remotely from my client I get:

Disconnected: disconnect_not_host

Any help? 
How can I tell a server to run a game without running a client on the same machine as the server?
Or how can I tell a server who is the "host" of the game is so he can connect first and create a game?

Thanks

**Comment by pandalabs-dev** [comment]
To further elaborate:

This will allow me to automate the system and create a bot in discord that can host games for other people

**Comment by honserver** [comment]
The first player to connect to the server is assigned as host, and IIRC no one else can join until that player starts a game (gets `disconnect_not_host` error). But that player can be anyone (does not need to be local). 

So just make sure your bot is the first to connect, or you can patch the dll to only allow your bot's IP for the first connection. 

(or you could disable the error and make it so it gives host to everyone who connects before a game is started, but that might cause problems)

**Comment by honserver** [comment]
(you will need to find someone else who can make changes like this. I only wanted to make the bare mimimum to make it possible to play HoN, any other changes will need to be done by others)

**Comment by honserver** [comment]
If any of those "frostburn staff" actually cared, they would leak a copy of the game server (anyone who had access to manage the servers would at least have access to binaries, if not source code), and this project would be unnecessary
